### PR TITLE
Mcpdf new

### PR DESCRIPTION
**Pull request by MSerrano0410**
Adding stamp and background functionality to mcpdf; trying to make the functionality and calls similar to pdftk.

### CODE REVIEW

**Comment by vog** [comment]
Thanks for the contribution. Unfortunately, your pull request contains the commit "Add FDF support", which can't be included due to unresolved issues:

https://github.com/m-click/mcpdf/pull/19#issuecomment-175560096

Please provide a pull request that is based on our current master branch.

In addition, the history is a bit chaotic, which should be cleaned up:

* Commit a8ba6f5 adds `*.class` files to the repository, which do not belong there.
* Commit a8ba6f5 introduces a lot of code that is then removed in 18ecd75. Maybe this should be a single, simpler commit?

Again, thanks for your effort, I'm looking forward to an improved pull request. This is a good step forward, and I'd love to see this integrated.

**Comment by MSerrano0410** [comment]
Dear Volker,

Hi! My apologies for the confusion -- I'm using mcpdf and expanding upon it
for my company, and adhir (who created the FDF support add-on) wanted FDF
support to be integrated as well.

I've separated the stamp/background add-ons with fdf support into a
separate, local branch, and will soon create a new pull request with just
the stamp/background additions. Also, if you could point out the unresolved
issues with the fdf support, I'd be happy to take a look at them separately!

Thanks again for your help and flexibility, and I'm looking forward to you
reviewing my new pull request after I submit it shortly!

Best,
Marvin

**Comment by vog** [comment]
> if you could point out the unresolved issues with the fdf support, I'd be happy to take a look at them separately! 

You can find my FDF review result as the latest comment in the FDF pull request:

* https://github.com/m-click/mcpdf/pull/19#issuecomment-175560096

**Comment by vog** [comment]
Closing this pull request, because it is superseded by pull request #21.

**Pull request closed without merging**
