### PR TITLE
Add FDF support to mcpdf

### PR DESCRIPTION
**Pull request by alokdhir**
Determine FDF vs XFDF by checking the first four bytes of input file.

### CODE REVIEW

**Comment by vog** [comment]
Thanks! This looks much better than #18. Remaining issues:

* Please keep `parseArgs()` simple. You don't need to change it at all. This function is only about parsing the user arguments, not about doing any actual work. For example, if there is an option that sets `config.formInputStream` to something different than `System.in` (e.g. a FileInputStream), that should be totally indepdenent of the `fill_form` option.
* Please put the "wrap around BufferedInputStream" logic into `execute()`, and put the FDF-recognition code into a new function `isFDF(BufferedInputStream inputStream)`.
* Please separate purely cosmetic changes (such as re-indenting the "throws" declarations) from the functional changes. These should be two commits, or even better, a separate pull request, as this doesn't have anything to do with FDF/XFDF.
* Please use uppercase "FDF"/"XFDF" instead of lowercase. Also, it may be good to state this upfront, so that the users sees right in the beginning of "fill_form" that this is about FDF as well as XFDF.

Note that it is sufficient to force-push your new contribution to your branch. No need to open a new pull request.

Thanks again for your effort! This is much appreciated.

**Comment by Jenselme** [comment]
@alokdhir This works great, thanks. Can you take into account @vog remarks so this can be merge?

**Comment by vog** [comment]
For your information: @MSerrano0410 took over and added stamping support (see #21), with the goal of polishing up FDF support after stamping. Unfortunately, it seems he got stuck when he was almost finished.

**Comment by vog** [comment]
Closing this for now. Feel free to open a new pull request if you want to contribute an improved patch!

**Pull request closed without merging**
