### PR TITLE
Stamp and background additions

### PR DESCRIPTION
**Pull request by MSerrano0410**
Adding stamp and background capabilities to mcpdf; made separate config function since pdftk's stamp and background capabilities did not use System.in or System.out, so this would make it look and function similarly to pdftk.

### CODE REVIEW

**Comment by vog** [comment]
Thanks, this looks much better than the previous pull request #20. Yet, there are still some issues.

Note that you don't need to create another pull request (although you can, if you want to). It may be easier if you simply force-push to your existing branch for this pull request.

This is my review result. First, there are some formal issues, which are necessary for a clean code history, and should be straight forward to fix:

* The indentation is a strange mix of spaces and tabs. This looks very confusing, not just in my editor, but also in the GitHub diff view. Please respect the existing indentation style, that is, 4 spaces per level, and no tabs.
* The same indentation issues are in the README.
* The commit contains a lot of noise, that is, changes which don't actually change anything. For example, all changes to "parseArgs()" and "execute()" are complete noise and distract from the real changes.
* A new variable "fdfHeader" is declared but never used, creating annoying compiler warnings.
* The class "FdfReader" is imported by never used, creating annoying compiler warnings.

Second, the code is more complicated than it needs to be, and duplicates a lot. It would be really appreciated if you could fix the following issues as well:

* The Config field pdf_sig serves a double-purpose (stamp and background), which makes the rest of the code more complicated than necessary. I propose to use two fields here, such as two File objects "stampFile" and "backgroundFile" (or two String objects "stampFilename" and "backgroundFilename").
* The functions "stamp()" and "background()" seem to have been copy&pasted from "execute()", instead of extenting "execute()" in the intended way. Among others, this makes the code harder to maintain, and removes the capability to perform "fill_form", "stamp" and "background" in a single command - although there is no reason to forbid that, and doing so would require even fewer code. Also this would allow "fill_form" output to filenames and "stamp" output to stdout, so all commands would have that flexibility.
* The function "parseArgsStampBackground()" seems to have been copy&pasted from "parseArgs()", instead of extended that function in the natural way. Same issue as above. Moreover, this is triggered by a "look-ahead" into the args array, which would have been completely unnecessary if the Config structure would have been closer to what is parsed (see above).
* The helper function "inArgs()" isn't needed at all, because the Java standard library already has a function for that: http://stackoverflow.com/a/1128728 (Moreover, this function won't be needed at all, once the Config structure is fixed as described above.)

**Comment by MSerrano0410** [comment]
Dear Vog,

Hi! Thank you for your feedback on this issue. I've done the following work
on this latest comment to pull request #21:

   - Merged parseArgsStampBackground into just parseArgs and extended that
   function as well as Config.class, as per your request.
   - Removed the if/else from the constructor of Main.class and
   incorporated the args for stamp/background into the existing parseArgs and
   execute functions.
   - Added the ability to call fill_form, stamp and background in the same
   command.
   - Removed inArgs since the arg handling is done in parseArgs.
   - Fixed the spacing issues in Main.class and Config.class to fit your
   specifications i.e. 4 spaces per level and no tabs.
   - Fixed spacing issues in README file and edited the call for
   stamp/background. You can now call stamp/background either alongside
   fill_form, or on its own.

I apologize that this took so long, and that there were so many issues with
the initial pull request -- it's what I get for working on this under 3
hours of sleep! Anyway, please let me know what you think of these changes,
and I look forward to your response!

Best,
Marvin

**Comment by vog** [comment]
Dear Marvin,

This looks very good! The total patch is now very small, elegant, flexible and almost clean. There are only the following minor issues left:

* The obsolete config property `pdf_sig` should be removed.
* There is an indentation issue left in Main.java, line 69.
* Please configure your editor so that it removed trailing spaces at end of line. This issue appears in Main.java as well as README.md.
* Please merge your changes into a single commit, so we have a clean history. You can do that either with `git rebase -i ...`, or with `git reset ...` followed by a new `git commit`. Then, use `git push -f`

**Comment by MSerrano0410** [comment]
Dear Volker,

Hi! I just removed pdf_sig from Config.class, fixed the indentation issue,
and modified my editor (Eclipse, only because it's familiar to me, open to
other suggestions for an IDE!) to remove trailing whitespaces when a file
is saved, so the whitespace issue should be gone.

Also, I've done a git reset before my latest commit, so that commit is the
only one in the history now.

Please let me know if there's anything else you'd like me to do before this
can be accepted! After this, I'd like to work on incorporating alok's FDF
changes into this code as well, in a new pull request, of course. I have
the list of fixes you wanted to see implemented into his work, so I'm happy
to do that once this pull request is accepted.

Best,
Marvin

**Comment by vog** [comment]
Very good progress, but some of the previous issues are still unsolved:

* The spacing issues are still present in README.md, probably you need to open and save that in your editor again.
* There are still 4 commits in the branch, rather than 1 commit that combines all changes. Probably the git commands aren't clear, so here are the exact commands to combine **the last 4 commits** via `git reset`:

```
git reset --soft HEAD~4
git commit -m 'Add stamp and background capabilities'
git push -f
```

Note that this works only for the last 4 commits. So if you add another commit before combining, you need to replace `HEAD~4` with `HEAD~5`.

**Comment by MSerrano0410** [comment]
Don't mind my latest pull request commit...for some reason, the reset
--soft HEAD-4 command is giving me issues. I did handle the spacing issue
issue in the README, but I'm struggling with the git commit changes. Still
working on that.

**Comment by MSerrano0410** [comment]
Dear Volker,

Hi! Sorry about the messy commit history -- I'm still relatively new to
Github, so I had some trouble using git reset, especially since HEAD~n
wasn't working for me. Finally, I resorted to pulling up the git log,
choosing the last commit you put in there, resetting to that, then
committing/force pushing. As you can see, it's now just one commit.

Also, I removed all trailing whitespace from README.md; I opened it in my
editor, removed all of them, saved, and then committed. I'm using Eclipse
and ensured that all trailing whitespace characters would be automatically
removed from here on in.

Please let me know what else I can do to make this commit an acceptable one!

Best,
Marvin

**Comment by MSerrano0410** [comment]
Dear Volker,

Hi! I was just checking in to see if there's anything else I could do to
make my most recent pull request commit acceptable to you. Please let me
know and I'll be happy to make any changes you feel are necessary!

Best,
Marvin

**Comment by vog** [comment]
Dear Marvin,

Sorry for the late response. These were quite busy weeks.

* The code looks very good. The rearranged imports are a bit strange, but perfectly okay for a merge.
* Something went wrong with the README.md file.

Regarding the README: There are a lot of "changes" in which the real changes are hidden. It seems that your editor added lots of manual line breaks:

https://github.com/m-click/mcpdf/pull/21/commits/51cedc40e1a739041a1ab222239206240bf992d3#diff-04c6e90faac2675aa89e2176d2eec7d8

Note that this is not just annoying, but actually changes some command line examples in the README by adding a line break where there should be no line break at the command line.

**Comment by vog** [comment]
It seems you were almost finished, except for this nasty editor issue. Do you need any assistance from me?

**Comment by MSerrano0410** [comment]
Dear Volker,

Hi! I'm so sorry for the late reply! These past few weeks have been insane
at work for me, so I haven't had time to sit down and figure this readme
spacing issue out!

I'm guessing that the spacing issue is an Eclipse-only thing. I've tried
mucking around with the spacing settings and such, but to no avail. I'm
going to try and edit the file using something else (maybe TextEdit since I
have a Mac) and see if the issue persists.

Out of curiosity, what did you view the README file in that showed the odd
spacing issues? I'd like to try and replicate what you're seeing, if at all
possible; Eclipse doesn't show oddities in that regard, so I'd like to make
sure that the spacing issues are resolved before pushing again.

Thanks for your patience, and here's hoping for a quick resolution!

Best,
Marvin

**Comment by vog** [comment]
Dear Marvin,

> Out of curiosity, what did you view the README file in that showed the odd spacing issues?

I just used the preview of GitHub. I clicked on the commit of your pull request, which is currently this one:

https://github.com/m-click/mcpdf/pull/21/commits/51cedc40e1a739041a1ab222239206240bf992d3

Then I saw lots of inserted newlines that do not belong there. For example, the diff shows that this one line:

    Mcpdf fixes PDFtk's unicode issues, so you can write Łódź into your forms. Mcpdf aims to become a drop-in replacement for PDFtk.

was replaced by these two lines:

    Mcpdf fixes PDFtk's unicode issues, so you can write Łódź into your
    forms. Mcpdf aims to become a drop-in replacement for PDFtk.

I expected to see nothing like that. The diff should contain just your real changes, i.e. the addition of your section "Add a stamp or background to a PDF file.", and nothing else.

**Comment by MSerrano0410** [comment]
Dear Volker,

Hi! I finally got the bright idea to directly commit the README on Github
since Eclipse was being stupid with its spacing and fixing the spacing in
another text editor didn't do the trick for some reason.

Let me know if it works for you!

- Marvin

**Comment by vog** [comment]
Dear Marvin,

This looks very good. I squashed your two commit into a single commit for better readability. It is now officially part of Mcpdf:

https://github.com/m-click/mcpdf/commit/08a6564bd8ce1fa48dc4c129a1ea7f2fe5546ec1

I also released a new version 0.2.4 that contains the new functionality.

**Comment by MSerrano0410** [comment]
Thank you good sir! I've been swamped at work, but I'll definitely make
some time as well to fix the pdf issues that alok had with his commit as
well -- that functionality would be incredibly useful for our mcpdf needs,
so it'd be amazing if we could work on adding that in too!

Thanks, and it's been a pleasure working with you!

Best,
Marvin

**Pull request closed without merging**
